### ISSUE TITLE
Windows x64 bit version

### ISSUE THREAD

**Issue by keith-hall** [eerohele/sublime-lxml#1]
Please can you include the windows x64 bit version of lxml. To avoid any need for compiling it yourself, you can download `lxml‑3.4.4‑cp33‑none‑win_amd64.whl` from http://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml (it is a zip file). I've tested by extracting this file to the `%AppData%\Sublime Text 3\Packages` folder on a Windows 7 x64 machine, and am able to import and use lxml in Sublime Text without any problems (`from lxml import etree` etc.)

(Thanks to Nat Dunn for this helpful article: https://www.webucator.com/blog/2015/03/how-to-install-lxml-for-python-3-on-64-bit-windows/)

**Comment by eerohele** [comment]
> I've tested by extracting this file to the %AppData%\Sublime Text 3\Packages folder on a Windows 7 x64 machine, and am able to import and use lxml in Sublime Text without any problems (from lxml import etree etc.)

It's been a while but I think I tried that on my Windows machine and it just didn't work for me. Nonetheless, I added the package you linked into the repo and created the 0.2.0 tag so that you can try it out. Please let me know whether it works for you. If it does, great — that means I can also make my own plugin available for Windows users.

**Comment by eerohele** [comment]
Ah, forgot that I'll need to remove the platform restriction for you to be able to try it out.

You should be able to give it a go once https://github.com/wbond/package_control_channel/pull/4960 is merged.

**Comment by keith-hall** [comment]
Thank you very much for your quick action :) I will let you know how I get on :+1:

**Comment by keith-hall** [comment]
I wonder, maybe I am mistaken, but I think the folder name should be `st3_windows_x64`, i.e. _windows_, not _win_, as per the hard to find info [here](https://packagecontrol.io/docs/dependencies) (search for `The valid list of operating systems is`)  and [an example](https://github.com/codexns/sublime-cffi).

**Comment by eerohele** [comment]
> I wonder, maybe I am mistaken, but I think the folder name should be st3_windows_x64, i.e. windows, not win

Yes, you're absolutely correct — thanks for pointing it out. Should be fixed now.

**Comment by keith-hall** [comment]
Success! It works for me, have tested on 2 different 64 bit win 7 installations/machines :)
Hopefully it will work for you too, it would be great to see your awesome Exalt plugin available on windows :) and hopefully that will make it more popular too ;)

Thank you very much - Kiitos!

**Comment by keith-hall** [comment]
I have closed the issue, but I don't mean to discourage further discussion :) I would be interested to hear how you get on :)

**Comment by eerohele** [comment]
Thanks for reporting back!

I tested it on one Windows 7 installation and it seems to work great for me, too. Not sure why it didn't work when I tried to modify `sys.path` directly.

In any case, many thanks for reporting the issue — I'll also make Exalt available on Windows x64, as you suggested.

**Comment by Kristinita** [comment]
@keith-hall , @eerohele , do you have any ideas, how I can use lxml in my Sublime Text plugins? I can successfully use lxml for global Python environment, but for local Sublime Text environment lxml doesn't work for me in Windows 10 64-bit.

See [**6.2 item of my question**](http://stackoverflow.com/q/42652998/5951529) for details.

Thanks.

**Comment by Kristinita** [comment]
@keith-hall , @eerohele , do you have any ideas, how I can use lxml in my Sublime Text plugins? I can successfully use lxml for global Python environment, but for local Sublime Text environment lxml doesn't work for me in Windows 10 64-bit. sublime-lxml doesn't work for me.

See [**6.2 item of my question**](http://stackoverflow.com/q/42652998/5951529) for details.

Thanks.

**Comment by keith-hall** [comment]
@Kristinita see https://github.com/eerohele/exalt/issues/6#issuecomment-297929415 - most likely the path ST is using includes your system installed packages, which won't be compatible with ST's Python version. You could try uninstalling the system-wide lxml package to see if it helps, or adjust the (order of items in the) path environment variable that ST is using.

**Comment by eerohele** [comment]
Sorry, I don't have any more insight into this issue. As far as I know, for all practical purposes, you're stuck with the Python version that comes bundled with Sublime Text.

The only way that I know of to use lxml (or any other plugin) is to package it as a [Package Control dependency] like sublime-lxml.

[Package Control dependency]: https://packagecontrol.io/docs/dependencies
