### ISSUE TITLE
lxml not compiled for Mac m1

### ISSUE THREAD

**Issue by ghost** [eerohele/sublime-lxml#11]
Description

Having installing the pytest plugin https://github.com/kaste/PyTest on sublime 4 I get the following error, but only after I close sublime and open it later:
Package Control: The dependency "lxml" is either not available on this platform or for this version of Sublime Text
lxml is installed on my Mac and in my venv

Everything works great until I quit and restart; then the plugin doesn't work

Here is what is in the log:

error: Package Control

1 missing dependency was just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly.
Package Control: The dependency 'lxml' is not currently installed; installing...
Package Control: The dependency "lxml" is either not available on this platform or for this version of Sublime Text
Package Control: The dependency 'lxml' has successfully been installed or updated
Package Control: All dependencies have been satisfied

Steps to reproduce

Install the above plugin
restart sublimetext
there is the error
It does it every time sublime starts
Expected behavior

No error

Actual behavior

See above

Environment

OS X Big Sur MacOS on M1 chip

**Comment by eerohele** [comment]
Thanks for the report. PR welcome for adding an M1-compatible version of lxml.

**Comment by Nothing4You** [comment]
@eerohele is that essentially just downloading the wheel and extracting it to the appropriate folder?

**Comment by Nothing4You** [comment]
it seems that sublime text still uses python 3.3.
lxml 4.3.0 dropped support for python 3.3, so 4.2.6 is the most recent version supporting python 3.3.
there is no cp33 build for macos on pypi for 4.2.6.
the most recent version with an (intel) macos wheel for cp33 on pypi is 4.2.1.

i guess this means the alternative would be to build a wheel for m1 (more or less) manually based on either 4.1.0 to just sync up with the rest of the currently used versions, updating all versions to 4.2.1 (didn't check cp33 for other os) or going for the most recent available version 4.2.6 on all platforms and building custom packages where needed?

**Comment by eerohele** [comment]
>@eerohele is that essentially just downloading the wheel and extracting it to the appropriate folder?

That should do it, yeah.

>it seems that sublime text still uses python 3.3.

That, or with ST4, you can opt in to Python 3.8. I don't think the Package Control dependency story is complete with regard to Python 3.8 dependencies yet, though.

Once it is, it might be possible to make M1 compatibility ST4 only, which might make things a bit easier.

>i guess this means the alternative would be to build a wheel for m1 (more or less) manually based on either 4.1.0 to just sync up with the rest of the currently used versions, updating all versions to 4.2.1 (didn't check cp33 for other os) or going for the most recent available version 4.2.6 on all platforms and building custom packages where needed?

I think so, yeah.

I remember trying to build lxml myself back in the day for a bunch of different OSs, and it wasn't a whole lot of fun.

FWIW, depending on what you're using this dependency for, you could also look into https://github.com/sublimelsp/LSP-lemminx.

**Comment by Nothing4You** [comment]
at least for my use I haven't played with LSP stuff yet, I was using the [XPath plugin](https://github.com/rosshadden/sublime-xpath) to get the xpath for the selection and navigate within the document using xpath.
I don't think that functionality is available in the LSP plugin.

I'll probably have a look into how to build wheels in the next days and see if I can get that into a usable state.

**Comment by Nothing4You** [comment]
Seems to be more complex to even just get python 3.3 running on a M1 mac :/

It's not available via homebrew and the installation of CPython 3.3.7 (or 3.3.6) via https://www.python.org/ftp/python/3.3.7/Python-3.3.7.tar.xz using asdf or pyenv fails.

As far as I can tell the sublime text plugin host however does provide a native python 3.3 build, so it seems to be doable, just not sure how complex that part would be.

Tips for getting python 3.3 running on macOS arm would be appreciated.

There's a related issue on pyenv about this in general, and it seems to be resolved for newer versions, but it doesn't seem that python versions this old receive much support anymore, especially considering that python 3.3 is already more than 4 years post end of life.
https://github.com/pyenv/pyenv/issues/1768

```
Warning: Python 3.3 was not found on your system...
Would you like us to install CPython 3.3.7 with Pyenv? [Y/n]: y
Installing CPython 3.3.7 with /opt/homebrew/bin/pyenv (this may take a few minutes)...
✘ Failed...
Something went wrong...
Downloading Python-3.3.7.tar.xz...
-> https://www.python.org/ftp/python/3.3.7/Python-3.3.7.tar.xz
Installing Python-3.3.7...

BUILD FAILED (OS X 12.0.1 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/3r/_4yk2mp92nj8t5bd_74yf8rw0000gp/T/python-build.20211115201732.10351
Results logged to /var/folders/3r/_4yk2mp92nj8t5bd_74yf8rw0000gp/T/python-build.20211115201732.10351.log

Last 10 log lines:
checking size of _Bool... 1
checking for uintptr_t... yes
checking size of uintptr_t... 8
checking size of off_t... 8
checking whether to enable large file support... no
checking size of time_t... 8
checking for pthread_t... yes
checking size of pthread_t... 8
configure: error: Unexpected output of 'arch' on OSX
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by Nothing4You** [comment]
why close this?

**Comment by alxmrs** [comment]
I can confirm that when I run `xcode-select --install`, I am able to install `lxml`.

**Comment by Nothing4You** [comment]
> I can confirm that when I run `xcode-select --install`, I am able to install `lxml`.

that has nothing to do with this.

**Comment by ludehon** [comment]
alxmrs solution worked for me
