### ISSUE TITLE
Update lxml 3.7.3 with libxml 2.9.4 possible?

### ISSUE THREAD

**Issue by deathaxe** [eerohele/sublime-lxml#6]
Is it possible to get an up to date lxml 3.7.3 package with libxml 2.9.4 bound to it?

I found lxml 3.7.3 package on https://pypi.python.org/pypi/lxml/3.7.3 but it was compiled with libxml 2.9.3 from 11-2015.

Quite a number of security fixes and memory leak issues have been fixed in the meanwhile.

**Comment by eerohele** [comment]
I'll look into it, but it should at least certainly be possible to update the Linux and OS X versions of lxml.

I never managed to compile the Windows version myself despite numerous attempts, so I'm not sure about that.

**Comment by eerohele** [comment]
I tried this over the weekend and statically compiling the Linux version of lxml went fine, but the macOS version not so much. I'll give it another try as soon as I find the time.

**Comment by deathaxe** [comment]
Thanks for all your efforts.

**Comment by eerohele** [comment]
All right, I think I managed to compile the macOS version on my parents' old Mac Mini.

@deathaxe: do you have the time and opportunity to help test the Linux version before I release it? All you'd need to do is clone this repo and temporarily replace the `lxml` directory in your Sublime Text packages directory with [this updated `lxml` directory](https://github.com/eerohele/sublime-lxml/tree/master/st3_linux_x64/lxml) and see whether e.g. Exalt still works OK for you. I think it should be enough to just see whether it reports any errors when validating a file, for example.

If you can't, no sweat — I'll try to figure out a way to do it myself.

**Comment by deathaxe** [comment]
Checked your master branch against Linux x64 and Windows 10 x64 with ST3 3131+ 

Exalt and XPath both work fine.

**Comment by eerohele** [comment]
Thanks! I'll run a few more tests when I can and then release a new version of the dependency.

**Comment by eerohele** [comment]
Sorry for the delay.

I've now released v0.4.0 of sublime-lxml, which uses lxml v3.7.3 on Linux and OS X.

If someone contributes a Windows version, I'd be happy to accept a PR, but I won't be able to compile it myself at the moment.

@deathaxe: thanks for the suggestion and the help. Please leave a comment here if you spot any issues while using sublime-lxml on Linux.

**Comment by deathaxe** [comment]
Thanks for your efforts, but unfortunately I'd need the Windows version updated as it is my primary platform.

Maybe we should at least use latest windows versions from https://pypi.python.org/pypi/lxml even though they use libxml 2.9.3 for some reason.

**Comment by eerohele** [comment]
I downloaded `lxml-3.7.3.win-amd64-py3.3.exe` from your link, opened it with 7zip and extracted the lxml folder into this repo. It seems to work for me:

```
reloading plugin Exalt.impl.plugin
reloading plugin Exalt.impl.validator
reloading plugin Exalt.impl.formatter
>>> from lxml import etree
Package Control: Skipping automatic upgrade, last run at 2017-06-14 09:11:50, next run at 2017-06-14 10:11:50 or after
>>> etree.LXML_VERSION
(3, 7, 3, 0)
```
Could you also give it a try before I release a new version? I pushed the new version into the master, so the same way as before. Thanks!

**Comment by eerohele** [comment]
Also, it would help if you could type this into the Sublime console to verify that it's actually using the correct version of lxml:

```python
from lxml import etree
etree.LXML_VERSION
```

**Comment by deathaxe** [comment]
Works like a charm. Thanks.

**Comment by eerohele** [comment]
0.5.0 deployed with the Win64 version of lxml updated to 3.7.3.
