### ISSUE TITLE
Linux x32 exists in the repo, but seems to be missing from Package Control

### ISSUE THREAD

**Issue by writeml** [eerohele/sublime-lxml#9]
This repository has a folder for `st3_linux_x32/lxml`, but the *lxml* entry in Package Control's `dependencies.json` file only lists the following platforms: `["osx-x64", "linux-x64", "windows-x64", "windows-x32"]`... (see below for the full entry, for reference)

Was `"linux-x32"` left-out intentionally? It seems like it should either be included, or removed from the code... Thanks!

``` json
{
    "name": "lxml",
    "load_order": "10",
    "description": "lxml",
    "author": "eerohele",
    "issues": "https://github.com/eerohele/sublime-lxml/issues",
    "releases": [
        {
            "base": "https://github.com/eerohele/sublime-lxml",
            "tags": true,
            "sublime_text": ">=3000",
            "platforms": ["osx-x64", "linux-x64", "windows-x64", "windows-x32"]
        }
    ]
},
```

**Comment by eerohele** [comment]
My memory's hazy on this, but I don't think it was left out intentionally.

Feel free to create a pull request to add `linux-x32` to wbond/package_control_channel if you have the time, or I can do it when I get the chance.

**Comment by writeml** [comment]
Thank you for the quick response! I've opened a PR here: https://github.com/wbond/package_control_channel/pull/7712
